### ISSUE TITLE
Request: Mouse sensitivity?

### ISSUE THREAD

**Issue by Zhnigo** [SuiMachine/White-Day---Sui-s-Hack#4]
Hello and thanks for your work!
I noticed that in-game sensitivity sliders only work with gamepad look and have no effect on the mouse. Would you consider fixing that with your hack in the future?

**Comment by SuiMachine** [comment]
https://github.com/SuiMachine/White-Day---Sui-s-Hack/commit/73e188844a410656ff8c044f47960155eea84a33
https://github.com/SuiMachine/White-Day---Sui-s-Hack/releases/tag/1.1

**Comment by Zhnigo** [comment]
i kneel

**Comment by Zhnigo** [comment]
i kneel
